CREATE TABLE dbo.CropInventory (
    CropID VARCHAR(50) NOT NULL PRIMARY KEY,
    CropName NVARCHAR(100) NOT NULL,
    Variety NVARCHAR(100),
    QuantityKg DECIMAL(12,2) NOT NULL CHECK (QuantityKg >= 0),
    HarvestDate DATE NOT NULL,
    ClimateExpFlag BIT NOT NULL DEFAULT 0,
    ExpectedSellPricePerKg DECIMAL(12,2),
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    ModifiedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE dbo.FarmInput (
    InputID VARCHAR(50) NOT NULL PRIMARY KEY,
    InputName NVARCHAR(100) NOT NULL,
    QuantityUnits INT NOT NULL CHECK (QuantityUnits >= 0),
    UnitType NVARCHAR(50) NOT NULL,
    ReorderThreshold INT NOT NULL DEFAULT 10,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    ModifiedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
